### PR TITLE
Small clean

### PR DESCRIPTION
**Pull request by JamMassey**
will update later but just so you can do, commits pretty much describe changes

very very little functional changes, is largely docs, typing and logging

### CODE REVIEW

**Comment by babymu5k** [comment]
did you check everything works?

**Comment by JamMassey** [comment]
> did you check everything works?

Nope not yet

**Comment by babymu5k** [comment]
alright ig koya will have to check if it works cause he has the dev and prod enviroment

**Comment by JamMassey** [comment]
> alright ig koya will have to check if it works cause he has the dev and prod enviroment

Am likely to add a second branch with more changes before I do my own local testing, but this is here for exposure/if you guys wanna move faster - I probably won't get that time for a few days

**Comment by babymu5k** [comment]
also @JamMassey would it be possible you could join the razdor dev discord 
https://discord.gg/MSrX5E8Fsp
for better coordation btw i am the client developer

**Comment by babymu5k** [comment]
> > alright ig koya will have to check if it works cause he has the dev and prod enviroment
> 
> Am likely to add a second branch with more changes before I do my own local testing, but this is here for exposure/if you guys wanna move faster - I probably won't get that time for a few days

alright i pretty sure koya told you how everything works on prod e.g mariadb, redis and stuff like that

**Comment by Serbirial** [comment]
Accepted with https://github.com/RazdorChat/api/commit/50c906f9e2c5c1d9f444a38d3e8fe1ccab2d555f

**Pull request merged**
